<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurveiSeeder extends Seeder
{
    public function run()
    {
        $surveiData = [
            // data 1
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei A',
                'lokasi_survei' => 'Lokasi A',
                'kro' => 'Kro A',
                'jadwal_kegiatan' => '2018-03-15',
                'jadwal_berakhir_kegiatan' => '2018-03-22',
                'status_survei' => rand(1, 3),
                'tim' => 'tim A',
                'rate_honor' => 35000,
            ],
            // data 2
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei B',
                'lokasi_survei' => 'Lokasi B',
                'kro' => 'Kro B',
                'jadwal_kegiatan' => '2019-07-10',
                'jadwal_berakhir_kegiatan' => '2019-07-18',
                'status_survei' => rand(1, 3),
                'tim' => 'tim B',
                'rate_honor' => 28000,
            ],
            // data 3
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei C',
                'lokasi_survei' => 'Lokasi C',
                'kro' => 'Kro C',
                'jadwal_kegiatan' => '2020-11-05',
                'jadwal_berakhir_kegiatan' => '2020-11-12',
                'status_survei' => rand(1, 3),
                'tim' => 'tim C',
                'rate_honor' => 42000,
            ],
            // data 4
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei D',
                'lokasi_survei' => 'Lokasi D',
                'kro' => 'Kro D',
                'jadwal_kegiatan' => '2021-02-20',
                'jadwal_berakhir_kegiatan' => '2021-02-27',
                'status_survei' => rand(1, 3),
                'tim' => 'tim D',
                'rate_honor' => 31000,
            ],
            // data 5
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei E',
                'lokasi_survei' => 'Lokasi E',
                'kro' => 'Kro E',
                'jadwal_kegiatan' => '2022-05-12',
                'jadwal_berakhir_kegiatan' => '2022-05-19',
                'status_survei' => rand(1, 3),
                'tim' => 'tim E',
                'rate_honor' => 45000,
            ],
            // data 6
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei F',
                'lokasi_survei' => 'Lokasi F',
                'kro' => 'Kro F',
                'jadwal_kegiatan' => '2023-09-08',
                'jadwal_berakhir_kegiatan' => '2023-09-15',
                'status_survei' => rand(1, 3),
                'tim' => 'tim F',
                'rate_honor' => 38000,
            ],
            // data 7
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei G',
                'lokasi_survei' => 'Lokasi G',
                'kro' => 'Kro G',
                'jadwal_kegiatan' => '2024-01-20',
                'jadwal_berakhir_kegiatan' => '2024-01-25',
                'status_survei' => rand(1, 3),
                'tim' => 'tim G',
                'rate_honor' => 29000,
            ],
            // data 8
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei H',
                'lokasi_survei' => 'Lokasi H',
                'kro' => 'Kro H',
                'jadwal_kegiatan' => '2025-04-10',
                'jadwal_berakhir_kegiatan' => '2025-04-15',
                'status_survei' => rand(1, 3),
                'tim' => 'tim H',
                'rate_honor' => 41000,
            ],
            // data 9
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei I',
                'lokasi_survei' => 'Lokasi I',
                'kro' => 'Kro I',
                'jadwal_kegiatan' => '2025-04-15',
                'jadwal_berakhir_kegiatan' => '2025-04-20',
                'status_survei' => rand(1, 3),
                'tim' => 'tim I',
                'rate_honor' => 41000,
            ],
            // data 10
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei J',
                'lokasi_survei' => 'Lokasi J',
                'kro' => 'Kro J',
                'jadwal_kegiatan' => '2025-05-10',
                'jadwal_berakhir_kegiatan' => '2025-05-20',
                'status_survei' => rand(1, 3),
                'tim' => 'tim J',
                'rate_honor' => 41000,
            ],
            // data 11
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei K',
                'lokasi_survei' => 'Lokasi K',
                'kro' => 'Kro K',
                'jadwal_kegiatan' => '2025-06-01',
                'jadwal_berakhir_kegiatan' => '2025-06-08',
                'status_survei' => rand(1, 3),
                'tim' => 'tim K',
                'rate_honor' => 36000,
            ],
            // data 12
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei L',
                'lokasi_survei' => 'Lokasi L',
                'kro' => 'Kro L',
                'jadwal_kegiatan' => '2025-07-15',
                'jadwal_berakhir_kegiatan' => '2025-07-22',
                'status_survei' => rand(1, 3),
                'tim' => 'tim L',
                'rate_honor' => 39000,
            ],
            // data 13
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei M',
                'lokasi_survei' => 'Lokasi M',
                'kro' => 'Kro M',
                'jadwal_kegiatan' => '2025-08-10',
                'jadwal_berakhir_kegiatan' => '2025-08-17',
                'status_survei' => rand(1, 3),
                'tim' => 'tim M',
                'rate_honor' => 32000,
            ],
            // data 14
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei N',
                'lokasi_survei' => 'Lokasi N',
                'kro' => 'Kro N',
                'jadwal_kegiatan' => '2025-09-05',
                'jadwal_berakhir_kegiatan' => '2025-09-12',
                'status_survei' => rand(1, 3),
                'tim' => 'tim N',
                'rate_honor' => 40000,
            ],
            // data 15
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei O',
                'lokasi_survei' => 'Lokasi O',
                'kro' => 'Kro O',
                'jadwal_kegiatan' => '2025-10-20',
                'jadwal_berakhir_kegiatan' => '2025-10-27',
                'status_survei' => rand(1, 3),
                'tim' => 'tim O',
                'rate_honor' => 37000,
            ],
            // data 16
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei P',
                'lokasi_survei' => 'Lokasi P',
                'kro' => 'Kro P',
                'jadwal_kegiatan' => '2025-11-15',
                'jadwal_berakhir_kegiatan' => '2025-11-22',
                'status_survei' => rand(1, 3),
                'tim' => 'tim P',
                'rate_honor' => 43000,
            ],
            // data 17
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei Q',
                'lokasi_survei' => 'Lokasi Q',
                'kro' => 'Kro Q',
                'jadwal_kegiatan' => '2020-12-01',
                'jadwal_berakhir_kegiatan' => '2020-12-08',
                'status_survei' => rand(1, 3),
                'tim' => 'tim Q',
                'rate_honor' => 34000,
            ],
            // data 18
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei R',
                'lokasi_survei' => 'Lokasi R',
                'kro' => 'Kro R',
                'jadwal_kegiatan' => '2020-01-10',
                'jadwal_berakhir_kegiatan' => '2020-01-17',
                'status_survei' => rand(1, 3),
                'tim' => 'tim R',
                'rate_honor' => 38000,
            ],
            // data 19
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei S',
                'lokasi_survei' => 'Lokasi S',
                'kro' => 'Kro S',
                'jadwal_kegiatan' => '2020-02-15',
                'jadwal_berakhir_kegiatan' => '2020-02-22',
                'status_survei' => rand(1, 3),
                'tim' => 'tim S',
                'rate_honor' => 41000,
            ],
            // data 20
            [
                'id_provinsi' => '35',
                'id_kabupaten' => '16',
                'id_kecamatan' => rand(1, 4),
                'id_desa' => rand(1, 4),
                'nama_survei' => 'Survei T',
                'lokasi_survei' => 'Lokasi T',
                'kro' => 'Kro T',
                'jadwal_kegiatan' => '2020-03-05',
                'jadwal_berakhir_kegiatan' => '2020-03-12',
                'status_survei' => rand(1, 3),
                'tim' => 'tim T',
                'rate_honor' => 39000,
            ],
            // Continue with the remaining 12 records following the same pattern
            // I've shown 8 records as an example, you would add the remaining 12
        ];

        DB::table('survei')->insert($surveiData);
    }
}